trace:
  property: "I AM DEFAULT"
spring:
  datasource:
    url: jdbc:mysql://localhost:30306/carnellj?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    password: root
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver